version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=CpZcVEXMtU04YG515b08
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=CpZcVEXMtU04YG515b08
    ports:
      - "5601:5601"

volumes:
  esdata1:
    driver: local

networks:
  default:
    driver: bridge
